- group: all
  vars:
    - product: trackside
    - tier: production

- group: postgresql-siteA
  vars:
    - efm_virtual_ip: 192.168.2.252
  hosts:
    - host: 192.168.2.245
    - host: 192.168.2.246
    - host: 192.168.2.247
      vars:
        - postgresql_replication_role: secondary
        - efm_promotable: False
  parents:
    - siteA
    - postgresql

- group: postgresql-siteB
  vars:
    - efm_virtual_ip: 192.168.2.253
  hosts:
    - host: 192.168.2.248
    - host: 192.168.2.249
    #- host: 192.168.2.250
    #  vars:
    #    - postgresql_replication_role: secondary
    #    - efm_promotable: False
  parents:
    - siteB
    - postgresql

- group: app-siteA
  hosts:
    - 10.10.0.11
    - 10.10.0.12
  parents:
    - siteA
    - app

- group: app-siteB
  hosts:
    - 10.8.0.11
    - 10.8.0.12
  parents:
    - siteB
    - app

- group: siteA
  vars:
    - placement: siteA

- group: siteB
  vars:
    - placement: siteB
